spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.39.64.137:3306/brandlogolab?createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: brandlogolab
    password: 2024mijin
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true